"""Create users_follow table

Revision ID: 2700624eb031
Revises: 806024b137c7
Create Date: 2023-11-14 12:39:59.077873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2700624eb031"
down_revision: Union[str, None] = "806024b137c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_follow",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_follower_id", sa.Integer(), nullable=False),
        sa.Column("user_following_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_follower_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_following_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_follow_id"), "users_follow", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_follow_id"), table_name="users_follow")
    op.drop_table("users_follow")
    # ### end Alembic commands ###
