"""Create tweet_medias table

Revision ID: cb0de43714c4
Revises: 214e665acd9f
Create Date: 2023-11-14 12:42:18.634670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb0de43714c4"
down_revision: Union[str, None] = "214e665acd9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tweet_medias",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tweet_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"], ["medias.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tweet_id"], ["tweets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tweet_medias_id"), "tweet_medias", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tweet_medias_id"), table_name="tweet_medias")
    op.drop_table("tweet_medias")
    # ### end Alembic commands ###
