services:
  frontend:
    image: nginx:1.25.3
    container_name: nginx
    restart: always
    networks:
      - web_network
    ports:
      - "80:8090"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/static:/www/data
      - ./frontend/medias:/www/data/medias
      - ./frontend/openapi.yml:/www/data/openapi.yml
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    networks:
      - web_network
      - db_network
    depends_on:
      - database
    volumes:
      - ./frontend/medias:/medias
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}

  database:
    image: postgres
    container_name: postgres
    restart: always
    networks:
      - db_network
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
      - ./postgres/init_db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432 # Only for test on local machine. You can get access from the network.

networks:
  web_network:
    driver: bridge

  db_network:
    driver: bridge
